
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { PostgrestQueryBuilder } from '@supabase/postgrest-js';

const SUPABASE_URL = "https://vsxnjnvwtgehagxbhdzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeG5qbnZ3dGdlaGFneGJoZHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODkzOTQsImV4cCI6MjA1ODE2NTM5NH0.4SEISsoUanD3lFIswUzBFo4ll3qC2Yd6mlN8rVwuyFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a type extension for the posts table since it's not in the auto-generated types
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database> {
    from<T extends string>(table: T): T extends keyof Database['public']['Tables'] 
      ? PostgrestQueryBuilder<Database['public']['Tables'][T]['Row']> 
      : T extends 'posts' 
        ? PostgrestQueryBuilder<{
            id: string;
            user_id: string;
            content: string;
            image_url: string | null;
            likes: number;
            comments_count: number;
            hashtags: string[];
            created_at: string;
          }> 
        : PostgrestQueryBuilder<any>;
  }
}
